# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waymo_toolkit/protos/annotation.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

import waymo_toolkit.protos.dataset_pb2
import waymo_toolkit.protos.label_pb2

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="waymo_toolkit/protos/annotation.proto",
    package="waymo.toolkit",
    serialized_pb=_b(
        '\n%waymo_toolkit/protos/annotation.proto\x12\rwaymo.toolkit\x1a waymo_toolkit/protos/label.proto\x1a"waymo_toolkit/protos/dataset.proto"\xcb\x02\n\nAnnotation\x12\'\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x16.waymo.toolkit.Context\x12\x18\n\x10timestamp_micros\x18\x02 \x01(\x03\x12&\n\x04pose\x18\x03 \x01(\x0b\x32\x18.waymo.toolkit.Transform\x12*\n\x0claser_labels\x18\x06 \x03(\x0b\x32\x14.waymo.toolkit.Label\x12;\n\x16projected_lidar_labels\x18\t \x03(\x0b\x32\x1b.waymo.toolkit.CameraLabels\x12\x32\n\rcamera_labels\x18\x08 \x03(\x0b\x32\x1b.waymo.toolkit.CameraLabels\x12\x35\n\x0eno_label_zones\x18\x07 \x03(\x0b\x32\x1d.waymo.toolkit.Polygon2dProto'  # noqa E501
    ),
    dependencies=[
        waymo_toolkit.protos.label_pb2.DESCRIPTOR,
        waymo_toolkit.protos.dataset_pb2.DESCRIPTOR,
    ],
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_ANNOTATION = _descriptor.Descriptor(
    name="Annotation",
    full_name="waymo.toolkit.Annotation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="context",
            full_name="waymo.toolkit.Annotation.context",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp_micros",
            full_name="waymo.toolkit.Annotation.timestamp_micros",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="pose",
            full_name="waymo.toolkit.Annotation.pose",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="laser_labels",
            full_name="waymo.toolkit.Annotation.laser_labels",
            index=3,
            number=6,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="projected_lidar_labels",
            full_name="waymo.toolkit.Annotation.projected_lidar_labels",
            index=4,
            number=9,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="camera_labels",
            full_name="waymo.toolkit.Annotation.camera_labels",
            index=5,
            number=8,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="no_label_zones",
            full_name="waymo.toolkit.Annotation.no_label_zones",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[],
    serialized_start=127,
    serialized_end=458,
)

_ANNOTATION.fields_by_name["context"].message_type = waymo_toolkit.protos.dataset_pb2._CONTEXT
_ANNOTATION.fields_by_name["pose"].message_type = waymo_toolkit.protos.dataset_pb2._TRANSFORM
_ANNOTATION.fields_by_name["laser_labels"].message_type = waymo_toolkit.protos.label_pb2._LABEL
_ANNOTATION.fields_by_name[
    "projected_lidar_labels"
].message_type = waymo_toolkit.protos.dataset_pb2._CAMERALABELS
_ANNOTATION.fields_by_name[
    "camera_labels"
].message_type = waymo_toolkit.protos.dataset_pb2._CAMERALABELS
_ANNOTATION.fields_by_name[
    "no_label_zones"
].message_type = waymo_toolkit.protos.label_pb2._POLYGON2DPROTO
DESCRIPTOR.message_types_by_name["Annotation"] = _ANNOTATION

Annotation = _reflection.GeneratedProtocolMessageType(
    "Annotation",
    (_message.Message,),
    dict(
        DESCRIPTOR=_ANNOTATION,
        __module__="waymo_toolkit.protos.annotation_pb2"
        # @@protoc_insertion_point(class_scope:waymo.toolkit.Annotation)
    ),
)
_sym_db.RegisterMessage(Annotation)


# @@protoc_insertion_point(module_scope)
